### PR TITLE
Did finish handling added.

### PR DESCRIPTION
**Pull request by drrost**
- mts_setValuesForKeysWithDictionaryDidFinish method added.
- Correspondent unit tests added.
- Unnecessary code deleted.

### CODE REVIEW

**Comment by vilanovi** [comment]
Hello @drrost, thanks for your changes.

I have to tell you that for long time I've been thinking to add this method, as I needed in mulitiple cases to know when the `mts_setValuesForKeysWithDictionary:` has finished.

However, I've always decided that it is not needed as you can just simply override the method `mts_setValuesForKeysWithDictionary:` in your `NSObject` subclasses.

```
- (void) mts_setValuesForKeysWithDictionary:(NSDictionary*)dictionary
{
    [super mts_setValuesForKeysWithDictionary:dictionary];
    // And here you can do the "Did Finish" actions.
}
```

The main reason that motivated me to follow this approach instead of implementing a custom method as you did is that you still would have to call `super` in the "didFinish" method, as the subclass hierarchy of your classes might  potentially have multiple layers. Therefore, something like this:

```
- (void)mts_setValuesForKeysWithDictionaryDidFinish
{
    [super mts_setValuesForKeysWithDictionaryDidFinish];
    // And here you can do the "Did Finish" actions.
}
```

Therefore, because I'm seing the same code complexity, even more becasue there is an extra method, I've decided to NOT add this method and simply override the `mts_setValuesForKeysWithDictionary:`. 

Does this make sense for you?

**Comment by drrost** [comment]
Hello @vilanovi !

I'm agree with you about code complexity. My solution solves slightly another task. It makes library using a little bit cleaner. For me, as for lib's user, it's not really clear where is the correct place where I can add my custom code that should be ran after the library finished its work. It is not easy to understand fast that `mts_setValuesForKeysWithDictionary:` is that place as soon as its name says nothing about that. 

I guess that adding method with a clear name increases lib's usability. But if you insist that it's not ok I can propose another solution. We may add a paragraph to README file with description how to add custom parsing to an `NSObjcet` in `mts_setValuesForKeysWithDictionary:` method. And it will add users more confidence where they may add those code.

What do you think about it?

**Comment by vilanovi** [comment]
Hi @drrost,

I understand your motivation, but I really think that the way to go is using the `mts_setValuesForKeysWithDictionary:` method. However, it is true that we should add a clear example in the README explaning how to do this. We can add some text and something like this:

```
@implementation MyCustomObject

// Override Motis method
- (void) mts_setValuesForKeysWithDictionary:(NSDictionary*)dictionary
{
    // Call super
    [super mts_setValuesForKeysWithDictionary:dictionary];

    // After mapping has been done, call custom method
    [self prefix_objectDidFinishMapping];
}

// Custom method to notify objects that mapping has finished
- (void)prefix_objectDidFinishMapping
{
    // Do any checks after mapping is finished.
}
@end
```

Would that work for you? I can update the readme file (or if you prefer, go ahead and do it and send a pull request).

**Comment by drrost** [comment]
Hi @vilanovi !

I've changed README.md and added a proper unit test. Please find them in pull request #30.

**Pull request closed without merging**
