### PR TITLE
Add default implementation of debugDescription in MTSMotisObject.

### PR DESCRIPTION
**Pull request by krzysztofkempa**
Default debugDescription in MTSMotisObject is very useful during debug.

### CODE REVIEW

**Comment by vilanovi** [comment]
Hi @krzysztofkempa ,

What about overriding the -description method directly and return the mts_description? Don't you think is better?

**Comment by krzysztofkempa** [comment]
Hi @vilanovi 

I have thought only in context of LLDB debugging and printing objects by "po" command. 
In case of overriding "-description" it is good idea but I have just tried to use "-mts_description" inside "-description" and it causes a crash because of  the loop. You call self.description inside "-mts_description" method so you cannot use "-mts_description" inside "-description". Please check below code from NSObject+Motis.m:

- (NSString*)mts_description
{
    return [self mts_descriptionWithIndentation:0];
}

- (NSString*)mts_descriptionWithIndentation:(NSInteger)indentation
{
    NSString *description = self.description; // -> It makes impossible to use -mts_description in -description
...
}

**Comment by vilanovi** [comment]
@krzysztofkempa, therefore, I'd suggest two options:

1. Either keep things as they are now. No need of a "debugDescription" method because we already have a "mts_description" method.

2. Either modify the implementation of "mts_descriptionWithIndentation" in order to not call a "-description" so we can override "-description" inside the "MTSMotisObject" and call the "mts_description".

Personally, I'd just do option 1 (which means to do nothing). However, I'm also open to go for option 2. Any preference?

Btw, I'm curious to know why and how are you using MTSMotisObject. I've added it to Motis some weeks ago but I don't really use it that often (with the category NSObject+Motis it is enough to do the JSON mapping, no need of a superclass).

Thanks,

**Comment by krzysztofkempa** [comment]
@vilanovi 

1. Default debugDescription is very convenient because during debug I can type only "po myObject" in LLDB debugger instead of "po [myObject mts_description]"

2. I think it is great idea remove dependency in mts_descriptionWithIdentation and add -mts_description into default -description implementation.

IMHO both options are useful but it is up to you.

In case of MTSMotisObject, I think you made great work because if I inherit, it provides me default NSCoding and NSCopying implementation, therefore I use it almost always.

**Comment by vilanovi** [comment]
I didn't know about the debugDescription. I just read about it now. Therefore it makes complete sense to add it.

Lets keep then the description without override. This way the debug description will display the origina lobject's description plus the motis description.

**Comment by vilanovi** [comment]
Changes available in CocoaPods under version 1.4.2

**Pull request merged**
