### PR TITLE
Add option to preserve mutability when setting value to NSMutableArray properties

### PR DESCRIPTION
**Pull request by dstranz**
How to replicate problem?
1) Create Motis object with NSMutableArray property
2) Set values with mts_setValuesForKeysWithDictionary
3) In mts_validateAutomaticallyValue:toClass:forKey: array is parsed in first lines, in `if ([*ioValue isKindOfClass:typeClass])` statement with `return YES` at the end.

Now arrays are not parsed at the beginning, they go to the existing `if/else` statement where mutability is properly checked.

### CODE REVIEW

**Comment by dstranz** [comment]
@vilanovi what do you think about this fix? :)

**Comment by vilanovi** [comment]
Hello, sorry for the delay. I'll try to give it a look before this Friday.

**Comment by vilanovi** [comment]
I've been reviewing your changes and I do agree on them, mostly. Let me explain myself:

- Line 1033: ok. We will return YES directly if the *ioValue class and classType matches and the class type of *ioValue is not an NSArray. In that case we will execute the validation.

- Line 1157: Here I do not agree. Mainly, I don't want to "return *ioValue != nil" as I need to check the exact type of the classArray and be sure that it is something known. Otherwise we risk that Motis returns an instnace of NSArray for something that it is not. Therefore, I'd rather add another "else if" statement and include the NSArray as the last type check. 

I'll merge your changes and then apply mine on top (this way you can pull).

Thanks,

**Comment by dstranz** [comment]
Yes, you are right. There should be another else if to check if typeClass is NSArray.

Thank you!

**Comment by vilanovi** [comment]
I've also added some tests to validate it (also with sets, ordered sets, mutable sets and mutable ordered sets).

New version 1.4.3 already pushed to cocoa pods.

Thanks!

**Pull request merged**
